/* Copyright 2018 SiFive, Inc */
/* SPDX-License-Identifier: Apache-2.0 */

#ifndef METAL__DRIVERS__BL_SECURE0_H
#define METAL__DRIVERS__BL_SECURE0_H

#include <stdlib.h>
#include <string.h>

#include <metal/compiler.h>
#include <metal/io.h>

#include <metal/clock.h>
#include <metal/interrupt.h>
#include <metal/secure.h>

#define SEC_ENG_SHA_BUSY_TIMEOUT_COUNT  (100 * 160 * 1000)
#define SEC_ENG_AES_BUSY_TIMEOUT_COUNT  (100 * 160 * 1000)

#define PUT_UINT32_BE(n, b, i)               \
    {                                        \
        (b)[(i)] = (uint8_t)((n) >> 24);     \
        (b)[(i) + 1] = (uint8_t)((n) >> 16); \
        (b)[(i) + 2] = (uint8_t)((n) >> 8);  \
        (b)[(i) + 3] = (uint8_t)((n));       \
    }

typedef struct sec_hash_device {
    uint32_t shaBuf[16];     /*!< Data not processed but in this temp buffer */
    uint32_t shaPadding[16]; /*!< Padding data */
    uint8_t type;                /*!< Sha has feed data */
} sec_hash_device_t;

typedef struct sec_aes_handle_t {
    SEC_ENG_AES_Type aesType;
    SEC_ENG_AES_Key_Type keyType;
} sec_aes_handle_t;

#define BL_SET_REG_BIT(val, bitname)              ((val) | (1U << bitname##_POS))
#define BL_CLR_REG_BIT(val, bitname)              ((val)&bitname##_UMSK)
#define BL_GET_REG_BITS_VAL(val, bitname)         (((val)&bitname##_MSK) >> bitname##_POS)
#define BL_SET_REG_BITS_VAL(val, bitname, bitval) (((val)&bitname##_UMSK) | ((uint32_t)(bitval) << bitname##_POS))
#define BL_IS_REG_BIT_SET(val, bitname)           (((val) & (1U << (bitname##_POS))) != 0)

#define BL_RDWD_FRM_BYTEP(p)   ((p[3] << 24) | (p[2] << 16) | (p[1] << 8) | (p[0]))

#define SEC_ENG_SE_SHA_CTRL_OFFSET     (0x0)
#define SEC_ENG_SE_SHA_BUSY            SEC_ENG_SE_SHA_BUSY
#define SEC_ENG_SE_SHA_BUSY_POS        (0U)
#define SEC_ENG_SE_SHA_BUSY_LEN        (1U)
#define SEC_ENG_SE_SHA_BUSY_MSK        (((1U << SEC_ENG_SE_SHA_BUSY_LEN) - 1) << SEC_ENG_SE_SHA_BUSY_POS)
#define SEC_ENG_SE_SHA_BUSY_UMSK       (~(((1U << SEC_ENG_SE_SHA_BUSY_LEN) - 1) << SEC_ENG_SE_SHA_BUSY_POS))
#define SEC_ENG_SE_SHA_TRIG_1T         SEC_ENG_SE_SHA_TRIG_1T
#define SEC_ENG_SE_SHA_TRIG_1T_POS     (1U)
#define SEC_ENG_SE_SHA_TRIG_1T_LEN     (1U)
#define SEC_ENG_SE_SHA_TRIG_1T_MSK     (((1U << SEC_ENG_SE_SHA_TRIG_1T_LEN) - 1) << SEC_ENG_SE_SHA_TRIG_1T_POS)
#define SEC_ENG_SE_SHA_TRIG_1T_UMSK    (~(((1U << SEC_ENG_SE_SHA_TRIG_1T_LEN) - 1) << SEC_ENG_SE_SHA_TRIG_1T_POS))
#define SEC_ENG_SE_SHA_MODE            SEC_ENG_SE_SHA_MODE
#define SEC_ENG_SE_SHA_MODE_POS        (2U)
#define SEC_ENG_SE_SHA_MODE_LEN        (3U)
#define SEC_ENG_SE_SHA_MODE_MSK        (((1U << SEC_ENG_SE_SHA_MODE_LEN) - 1) << SEC_ENG_SE_SHA_MODE_POS)
#define SEC_ENG_SE_SHA_MODE_UMSK       (~(((1U << SEC_ENG_SE_SHA_MODE_LEN) - 1) << SEC_ENG_SE_SHA_MODE_POS))
#define SEC_ENG_SE_SHA_EN              SEC_ENG_SE_SHA_EN
#define SEC_ENG_SE_SHA_EN_POS          (5U)
#define SEC_ENG_SE_SHA_EN_LEN          (1U)
#define SEC_ENG_SE_SHA_EN_MSK          (((1U << SEC_ENG_SE_SHA_EN_LEN) - 1) << SEC_ENG_SE_SHA_EN_POS)
#define SEC_ENG_SE_SHA_EN_UMSK         (~(((1U << SEC_ENG_SE_SHA_EN_LEN) - 1) << SEC_ENG_SE_SHA_EN_POS))
#define SEC_ENG_SE_SHA_HASH_SEL        SEC_ENG_SE_SHA_HASH_SEL
#define SEC_ENG_SE_SHA_HASH_SEL_POS    (6U)
#define SEC_ENG_SE_SHA_HASH_SEL_LEN    (1U)
#define SEC_ENG_SE_SHA_HASH_SEL_MSK    (((1U << SEC_ENG_SE_SHA_HASH_SEL_LEN) - 1) << SEC_ENG_SE_SHA_HASH_SEL_POS)
#define SEC_ENG_SE_SHA_HASH_SEL_UMSK   (~(((1U << SEC_ENG_SE_SHA_HASH_SEL_LEN) - 1) << SEC_ENG_SE_SHA_HASH_SEL_POS))
#define SEC_ENG_SE_SHA_INT             SEC_ENG_SE_SHA_INT
#define SEC_ENG_SE_SHA_INT_POS         (8U)
#define SEC_ENG_SE_SHA_INT_LEN         (1U)
#define SEC_ENG_SE_SHA_INT_MSK         (((1U << SEC_ENG_SE_SHA_INT_LEN) - 1) << SEC_ENG_SE_SHA_INT_POS)
#define SEC_ENG_SE_SHA_INT_UMSK        (~(((1U << SEC_ENG_SE_SHA_INT_LEN) - 1) << SEC_ENG_SE_SHA_INT_POS))
#define SEC_ENG_SE_SHA_INT_CLR_1T      SEC_ENG_SE_SHA_INT_CLR_1T
#define SEC_ENG_SE_SHA_INT_CLR_1T_POS  (9U)
#define SEC_ENG_SE_SHA_INT_CLR_1T_LEN  (1U)
#define SEC_ENG_SE_SHA_INT_CLR_1T_MSK  (((1U << SEC_ENG_SE_SHA_INT_CLR_1T_LEN) - 1) << SEC_ENG_SE_SHA_INT_CLR_1T_POS)
#define SEC_ENG_SE_SHA_INT_CLR_1T_UMSK (~(((1U << SEC_ENG_SE_SHA_INT_CLR_1T_LEN) - 1) << SEC_ENG_SE_SHA_INT_CLR_1T_POS))
#define SEC_ENG_SE_SHA_INT_SET_1T      SEC_ENG_SE_SHA_INT_SET_1T
#define SEC_ENG_SE_SHA_INT_SET_1T_POS  (10U)
#define SEC_ENG_SE_SHA_INT_SET_1T_LEN  (1U)
#define SEC_ENG_SE_SHA_INT_SET_1T_MSK  (((1U << SEC_ENG_SE_SHA_INT_SET_1T_LEN) - 1) << SEC_ENG_SE_SHA_INT_SET_1T_POS)
#define SEC_ENG_SE_SHA_INT_SET_1T_UMSK (~(((1U << SEC_ENG_SE_SHA_INT_SET_1T_LEN) - 1) << SEC_ENG_SE_SHA_INT_SET_1T_POS))
#define SEC_ENG_SE_SHA_INT_MASK        SEC_ENG_SE_SHA_INT_MASK
#define SEC_ENG_SE_SHA_INT_MASK_POS    (11U)
#define SEC_ENG_SE_SHA_INT_MASK_LEN    (1U)
#define SEC_ENG_SE_SHA_INT_MASK_MSK    (((1U << SEC_ENG_SE_SHA_INT_MASK_LEN) - 1) << SEC_ENG_SE_SHA_INT_MASK_POS)
#define SEC_ENG_SE_SHA_INT_MASK_UMSK   (~(((1U << SEC_ENG_SE_SHA_INT_MASK_LEN) - 1) << SEC_ENG_SE_SHA_INT_MASK_POS))
#define SEC_ENG_SE_SHA_LINK_MODE       SEC_ENG_SE_SHA_LINK_MODE
#define SEC_ENG_SE_SHA_LINK_MODE_POS   (15U)
#define SEC_ENG_SE_SHA_LINK_MODE_LEN   (1U)
#define SEC_ENG_SE_SHA_LINK_MODE_MSK   (((1U << SEC_ENG_SE_SHA_LINK_MODE_LEN) - 1) << SEC_ENG_SE_SHA_LINK_MODE_POS)
#define SEC_ENG_SE_SHA_LINK_MODE_UMSK  (~(((1U << SEC_ENG_SE_SHA_LINK_MODE_LEN) - 1) << SEC_ENG_SE_SHA_LINK_MODE_POS))
#define SEC_ENG_SE_SHA_MSG_LEN         SEC_ENG_SE_SHA_MSG_LEN
#define SEC_ENG_SE_SHA_MSG_LEN_POS     (16U)
#define SEC_ENG_SE_SHA_MSG_LEN_LEN     (16U)
#define SEC_ENG_SE_SHA_MSG_LEN_MSK     (((1U << SEC_ENG_SE_SHA_MSG_LEN_LEN) - 1) << SEC_ENG_SE_SHA_MSG_LEN_POS)
#define SEC_ENG_SE_SHA_MSG_LEN_UMSK    (~(((1U << SEC_ENG_SE_SHA_MSG_LEN_LEN) - 1) << SEC_ENG_SE_SHA_MSG_LEN_POS))

#define SEC_ENG_SE_SHA_0_CTRL_OFFSET     (0x0)
#define SEC_ENG_SE_SHA_0_BUSY            SEC_ENG_SE_SHA_0_BUSY
#define SEC_ENG_SE_SHA_0_BUSY_POS        (0U)
#define SEC_ENG_SE_SHA_0_BUSY_LEN        (1U)
#define SEC_ENG_SE_SHA_0_BUSY_MSK        (((1U << SEC_ENG_SE_SHA_0_BUSY_LEN) - 1) << SEC_ENG_SE_SHA_0_BUSY_POS)
#define SEC_ENG_SE_SHA_0_BUSY_UMSK       (~(((1U << SEC_ENG_SE_SHA_0_BUSY_LEN) - 1) << SEC_ENG_SE_SHA_0_BUSY_POS))
#define SEC_ENG_SE_SHA_0_TRIG_1T         SEC_ENG_SE_SHA_0_TRIG_1T
#define SEC_ENG_SE_SHA_0_TRIG_1T_POS     (1U)
#define SEC_ENG_SE_SHA_0_TRIG_1T_LEN     (1U)
#define SEC_ENG_SE_SHA_0_TRIG_1T_MSK     (((1U << SEC_ENG_SE_SHA_0_TRIG_1T_LEN) - 1) << SEC_ENG_SE_SHA_0_TRIG_1T_POS)
#define SEC_ENG_SE_SHA_0_TRIG_1T_UMSK    (~(((1U << SEC_ENG_SE_SHA_0_TRIG_1T_LEN) - 1) << SEC_ENG_SE_SHA_0_TRIG_1T_POS))
#define SEC_ENG_SE_SHA_0_MODE            SEC_ENG_SE_SHA_0_MODE
#define SEC_ENG_SE_SHA_0_MODE_POS        (2U)
#define SEC_ENG_SE_SHA_0_MODE_LEN        (3U)
#define SEC_ENG_SE_SHA_0_MODE_MSK        (((1U << SEC_ENG_SE_SHA_0_MODE_LEN) - 1) << SEC_ENG_SE_SHA_0_MODE_POS)
#define SEC_ENG_SE_SHA_0_MODE_UMSK       (~(((1U << SEC_ENG_SE_SHA_0_MODE_LEN) - 1) << SEC_ENG_SE_SHA_0_MODE_POS))
#define SEC_ENG_SE_SHA_0_EN              SEC_ENG_SE_SHA_0_EN
#define SEC_ENG_SE_SHA_0_EN_POS          (5U)
#define SEC_ENG_SE_SHA_0_EN_LEN          (1U)
#define SEC_ENG_SE_SHA_0_EN_MSK          (((1U << SEC_ENG_SE_SHA_0_EN_LEN) - 1) << SEC_ENG_SE_SHA_0_EN_POS)
#define SEC_ENG_SE_SHA_0_EN_UMSK         (~(((1U << SEC_ENG_SE_SHA_0_EN_LEN) - 1) << SEC_ENG_SE_SHA_0_EN_POS))
#define SEC_ENG_SE_SHA_0_HASH_SEL        SEC_ENG_SE_SHA_0_HASH_SEL
#define SEC_ENG_SE_SHA_0_HASH_SEL_POS    (6U)
#define SEC_ENG_SE_SHA_0_HASH_SEL_LEN    (1U)
#define SEC_ENG_SE_SHA_0_HASH_SEL_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_SEL_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_SEL_POS)
#define SEC_ENG_SE_SHA_0_HASH_SEL_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_SEL_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_SEL_POS))
#define SEC_ENG_SE_SHA_0_INT             SEC_ENG_SE_SHA_0_INT
#define SEC_ENG_SE_SHA_0_INT_POS         (8U)
#define SEC_ENG_SE_SHA_0_INT_LEN         (1U)
#define SEC_ENG_SE_SHA_0_INT_MSK         (((1U << SEC_ENG_SE_SHA_0_INT_LEN) - 1) << SEC_ENG_SE_SHA_0_INT_POS)
#define SEC_ENG_SE_SHA_0_INT_UMSK        (~(((1U << SEC_ENG_SE_SHA_0_INT_LEN) - 1) << SEC_ENG_SE_SHA_0_INT_POS))
#define SEC_ENG_SE_SHA_0_INT_CLR_1T      SEC_ENG_SE_SHA_0_INT_CLR_1T
#define SEC_ENG_SE_SHA_0_INT_CLR_1T_POS  (9U)
#define SEC_ENG_SE_SHA_0_INT_CLR_1T_LEN  (1U)
#define SEC_ENG_SE_SHA_0_INT_CLR_1T_MSK  (((1U << SEC_ENG_SE_SHA_0_INT_CLR_1T_LEN) - 1) << SEC_ENG_SE_SHA_0_INT_CLR_1T_POS)
#define SEC_ENG_SE_SHA_0_INT_CLR_1T_UMSK (~(((1U << SEC_ENG_SE_SHA_0_INT_CLR_1T_LEN) - 1) << SEC_ENG_SE_SHA_0_INT_CLR_1T_POS))
#define SEC_ENG_SE_SHA_0_INT_SET_1T      SEC_ENG_SE_SHA_0_INT_SET_1T
#define SEC_ENG_SE_SHA_0_INT_SET_1T_POS  (10U)
#define SEC_ENG_SE_SHA_0_INT_SET_1T_LEN  (1U)
#define SEC_ENG_SE_SHA_0_INT_SET_1T_MSK  (((1U << SEC_ENG_SE_SHA_0_INT_SET_1T_LEN) - 1) << SEC_ENG_SE_SHA_0_INT_SET_1T_POS)
#define SEC_ENG_SE_SHA_0_INT_SET_1T_UMSK (~(((1U << SEC_ENG_SE_SHA_0_INT_SET_1T_LEN) - 1) << SEC_ENG_SE_SHA_0_INT_SET_1T_POS))
#define SEC_ENG_SE_SHA_0_INT_MASK        SEC_ENG_SE_SHA_0_INT_MASK
#define SEC_ENG_SE_SHA_0_INT_MASK_POS    (11U)
#define SEC_ENG_SE_SHA_0_INT_MASK_LEN    (1U)
#define SEC_ENG_SE_SHA_0_INT_MASK_MSK    (((1U << SEC_ENG_SE_SHA_0_INT_MASK_LEN) - 1) << SEC_ENG_SE_SHA_0_INT_MASK_POS)
#define SEC_ENG_SE_SHA_0_INT_MASK_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_INT_MASK_LEN) - 1) << SEC_ENG_SE_SHA_0_INT_MASK_POS))
#define SEC_ENG_SE_SHA_0_LINK_MODE       SEC_ENG_SE_SHA_0_LINK_MODE
#define SEC_ENG_SE_SHA_0_LINK_MODE_POS   (15U)
#define SEC_ENG_SE_SHA_0_LINK_MODE_LEN   (1U)
#define SEC_ENG_SE_SHA_0_LINK_MODE_MSK   (((1U << SEC_ENG_SE_SHA_0_LINK_MODE_LEN) - 1) << SEC_ENG_SE_SHA_0_LINK_MODE_POS)
#define SEC_ENG_SE_SHA_0_LINK_MODE_UMSK  (~(((1U << SEC_ENG_SE_SHA_0_LINK_MODE_LEN) - 1) << SEC_ENG_SE_SHA_0_LINK_MODE_POS))
#define SEC_ENG_SE_SHA_0_MSG_LEN         SEC_ENG_SE_SHA_0_MSG_LEN
#define SEC_ENG_SE_SHA_0_MSG_LEN_POS     (16U)
#define SEC_ENG_SE_SHA_0_MSG_LEN_LEN     (16U)
#define SEC_ENG_SE_SHA_0_MSG_LEN_MSK     (((1U << SEC_ENG_SE_SHA_0_MSG_LEN_LEN) - 1) << SEC_ENG_SE_SHA_0_MSG_LEN_POS)
#define SEC_ENG_SE_SHA_0_MSG_LEN_UMSK    (~(((1U << SEC_ENG_SE_SHA_0_MSG_LEN_LEN) - 1) << SEC_ENG_SE_SHA_0_MSG_LEN_POS))

/* 0x4 : se_sha_0_msa */
#define SEC_ENG_SE_SHA_0_MSA_OFFSET (0x4)
#define SEC_ENG_SE_SHA_0_MSA        SEC_ENG_SE_SHA_0_MSA
#define SEC_ENG_SE_SHA_0_MSA_POS    (0U)
#define SEC_ENG_SE_SHA_0_MSA_LEN    (32U)
#define SEC_ENG_SE_SHA_0_MSA_MSK    (((1U << SEC_ENG_SE_SHA_0_MSA_LEN) - 1) << SEC_ENG_SE_SHA_0_MSA_POS)
#define SEC_ENG_SE_SHA_0_MSA_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_MSA_LEN) - 1) << SEC_ENG_SE_SHA_0_MSA_POS))

/* 0x8 : se_sha_0_status */
#define SEC_ENG_SE_SHA_0_STATUS_OFFSET (0x8)
#define SEC_ENG_SE_SHA_0_STATUS        SEC_ENG_SE_SHA_0_STATUS
#define SEC_ENG_SE_SHA_0_STATUS_POS    (0U)
#define SEC_ENG_SE_SHA_0_STATUS_LEN    (32U)
#define SEC_ENG_SE_SHA_0_STATUS_MSK    (((1U << SEC_ENG_SE_SHA_0_STATUS_LEN) - 1) << SEC_ENG_SE_SHA_0_STATUS_POS)
#define SEC_ENG_SE_SHA_0_STATUS_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_STATUS_LEN) - 1) << SEC_ENG_SE_SHA_0_STATUS_POS))

/* 0xC : se_sha_0_endian */
#define SEC_ENG_SE_SHA_0_ENDIAN_OFFSET    (0xC)
#define SEC_ENG_SE_SHA_0_DOUT_ENDIAN      SEC_ENG_SE_SHA_0_DOUT_ENDIAN
#define SEC_ENG_SE_SHA_0_DOUT_ENDIAN_POS  (0U)
#define SEC_ENG_SE_SHA_0_DOUT_ENDIAN_LEN  (1U)
#define SEC_ENG_SE_SHA_0_DOUT_ENDIAN_MSK  (((1U << SEC_ENG_SE_SHA_0_DOUT_ENDIAN_LEN) - 1) << SEC_ENG_SE_SHA_0_DOUT_ENDIAN_POS)
#define SEC_ENG_SE_SHA_0_DOUT_ENDIAN_UMSK (~(((1U << SEC_ENG_SE_SHA_0_DOUT_ENDIAN_LEN) - 1) << SEC_ENG_SE_SHA_0_DOUT_ENDIAN_POS))

/* 0x10 : se_sha_0_hash_l_0 */
#define SEC_ENG_SE_SHA_0_HASH_L_0_OFFSET (0x10)
#define SEC_ENG_SE_SHA_0_HASH_L_0        SEC_ENG_SE_SHA_0_HASH_L_0
#define SEC_ENG_SE_SHA_0_HASH_L_0_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_L_0_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_L_0_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_L_0_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_0_POS)
#define SEC_ENG_SE_SHA_0_HASH_L_0_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_L_0_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_0_POS))

/* 0x14 : se_sha_0_hash_l_1 */
#define SEC_ENG_SE_SHA_0_HASH_L_1_OFFSET (0x14)
#define SEC_ENG_SE_SHA_0_HASH_L_1        SEC_ENG_SE_SHA_0_HASH_L_1
#define SEC_ENG_SE_SHA_0_HASH_L_1_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_L_1_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_L_1_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_L_1_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_1_POS)
#define SEC_ENG_SE_SHA_0_HASH_L_1_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_L_1_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_1_POS))

/* 0x18 : se_sha_0_hash_l_2 */
#define SEC_ENG_SE_SHA_0_HASH_L_2_OFFSET (0x18)
#define SEC_ENG_SE_SHA_0_HASH_L_2        SEC_ENG_SE_SHA_0_HASH_L_2
#define SEC_ENG_SE_SHA_0_HASH_L_2_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_L_2_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_L_2_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_L_2_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_2_POS)
#define SEC_ENG_SE_SHA_0_HASH_L_2_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_L_2_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_2_POS))

/* 0x1C : se_sha_0_hash_l_3 */
#define SEC_ENG_SE_SHA_0_HASH_L_3_OFFSET (0x1C)
#define SEC_ENG_SE_SHA_0_HASH_L_3        SEC_ENG_SE_SHA_0_HASH_L_3
#define SEC_ENG_SE_SHA_0_HASH_L_3_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_L_3_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_L_3_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_L_3_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_3_POS)
#define SEC_ENG_SE_SHA_0_HASH_L_3_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_L_3_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_3_POS))

/* 0x20 : se_sha_0_hash_l_4 */
#define SEC_ENG_SE_SHA_0_HASH_L_4_OFFSET (0x20)
#define SEC_ENG_SE_SHA_0_HASH_L_4        SEC_ENG_SE_SHA_0_HASH_L_4
#define SEC_ENG_SE_SHA_0_HASH_L_4_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_L_4_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_L_4_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_L_4_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_4_POS)
#define SEC_ENG_SE_SHA_0_HASH_L_4_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_L_4_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_4_POS))

/* 0x24 : se_sha_0_hash_l_5 */
#define SEC_ENG_SE_SHA_0_HASH_L_5_OFFSET (0x24)
#define SEC_ENG_SE_SHA_0_HASH_L_5        SEC_ENG_SE_SHA_0_HASH_L_5
#define SEC_ENG_SE_SHA_0_HASH_L_5_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_L_5_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_L_5_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_L_5_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_5_POS)
#define SEC_ENG_SE_SHA_0_HASH_L_5_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_L_5_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_5_POS))

/* 0x28 : se_sha_0_hash_l_6 */
#define SEC_ENG_SE_SHA_0_HASH_L_6_OFFSET (0x28)
#define SEC_ENG_SE_SHA_0_HASH_L_6        SEC_ENG_SE_SHA_0_HASH_L_6
#define SEC_ENG_SE_SHA_0_HASH_L_6_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_L_6_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_L_6_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_L_6_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_6_POS)
#define SEC_ENG_SE_SHA_0_HASH_L_6_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_L_6_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_6_POS))

/* 0x2C : se_sha_0_hash_l_7 */
#define SEC_ENG_SE_SHA_0_HASH_L_7_OFFSET (0x2C)
#define SEC_ENG_SE_SHA_0_HASH_L_7        SEC_ENG_SE_SHA_0_HASH_L_7
#define SEC_ENG_SE_SHA_0_HASH_L_7_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_L_7_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_L_7_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_L_7_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_7_POS)
#define SEC_ENG_SE_SHA_0_HASH_L_7_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_L_7_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_L_7_POS))

/* 0x30 : se_sha_0_hash_h_0 */
#define SEC_ENG_SE_SHA_0_HASH_H_0_OFFSET (0x30)
#define SEC_ENG_SE_SHA_0_HASH_H_0        SEC_ENG_SE_SHA_0_HASH_H_0
#define SEC_ENG_SE_SHA_0_HASH_H_0_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_H_0_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_H_0_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_H_0_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_0_POS)
#define SEC_ENG_SE_SHA_0_HASH_H_0_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_H_0_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_0_POS))

/* 0x34 : se_sha_0_hash_h_1 */
#define SEC_ENG_SE_SHA_0_HASH_H_1_OFFSET (0x34)
#define SEC_ENG_SE_SHA_0_HASH_H_1        SEC_ENG_SE_SHA_0_HASH_H_1
#define SEC_ENG_SE_SHA_0_HASH_H_1_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_H_1_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_H_1_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_H_1_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_1_POS)
#define SEC_ENG_SE_SHA_0_HASH_H_1_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_H_1_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_1_POS))

/* 0x38 : se_sha_0_hash_h_2 */
#define SEC_ENG_SE_SHA_0_HASH_H_2_OFFSET (0x38)
#define SEC_ENG_SE_SHA_0_HASH_H_2        SEC_ENG_SE_SHA_0_HASH_H_2
#define SEC_ENG_SE_SHA_0_HASH_H_2_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_H_2_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_H_2_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_H_2_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_2_POS)
#define SEC_ENG_SE_SHA_0_HASH_H_2_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_H_2_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_2_POS))

/* 0x3C : se_sha_0_hash_h_3 */
#define SEC_ENG_SE_SHA_0_HASH_H_3_OFFSET (0x3C)
#define SEC_ENG_SE_SHA_0_HASH_H_3        SEC_ENG_SE_SHA_0_HASH_H_3
#define SEC_ENG_SE_SHA_0_HASH_H_3_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_H_3_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_H_3_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_H_3_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_3_POS)
#define SEC_ENG_SE_SHA_0_HASH_H_3_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_H_3_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_3_POS))

/* 0x40 : se_sha_0_hash_h_4 */
#define SEC_ENG_SE_SHA_0_HASH_H_4_OFFSET (0x40)
#define SEC_ENG_SE_SHA_0_HASH_H_4        SEC_ENG_SE_SHA_0_HASH_H_4
#define SEC_ENG_SE_SHA_0_HASH_H_4_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_H_4_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_H_4_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_H_4_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_4_POS)
#define SEC_ENG_SE_SHA_0_HASH_H_4_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_H_4_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_4_POS))

/* 0x44 : se_sha_0_hash_h_5 */
#define SEC_ENG_SE_SHA_0_HASH_H_5_OFFSET (0x44)
#define SEC_ENG_SE_SHA_0_HASH_H_5        SEC_ENG_SE_SHA_0_HASH_H_5
#define SEC_ENG_SE_SHA_0_HASH_H_5_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_H_5_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_H_5_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_H_5_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_5_POS)
#define SEC_ENG_SE_SHA_0_HASH_H_5_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_H_5_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_5_POS))

/* 0x48 : se_sha_0_hash_h_6 */
#define SEC_ENG_SE_SHA_0_HASH_H_6_OFFSET (0x48)
#define SEC_ENG_SE_SHA_0_HASH_H_6        SEC_ENG_SE_SHA_0_HASH_H_6
#define SEC_ENG_SE_SHA_0_HASH_H_6_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_H_6_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_H_6_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_H_6_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_6_POS)
#define SEC_ENG_SE_SHA_0_HASH_H_6_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_H_6_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_6_POS))

/* 0x4C : se_sha_0_hash_h_7 */
#define SEC_ENG_SE_SHA_0_HASH_H_7_OFFSET (0x4C)
#define SEC_ENG_SE_SHA_0_HASH_H_7        SEC_ENG_SE_SHA_0_HASH_H_7
#define SEC_ENG_SE_SHA_0_HASH_H_7_POS    (0U)
#define SEC_ENG_SE_SHA_0_HASH_H_7_LEN    (32U)
#define SEC_ENG_SE_SHA_0_HASH_H_7_MSK    (((1U << SEC_ENG_SE_SHA_0_HASH_H_7_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_7_POS)
#define SEC_ENG_SE_SHA_0_HASH_H_7_UMSK   (~(((1U << SEC_ENG_SE_SHA_0_HASH_H_7_LEN) - 1) << SEC_ENG_SE_SHA_0_HASH_H_7_POS))

/* 0x50 : se_sha_0_link */
#define SEC_ENG_SE_SHA_0_LINK_OFFSET (0x50)
#define SEC_ENG_SE_SHA_0_LCA         SEC_ENG_SE_SHA_0_LCA
#define SEC_ENG_SE_SHA_0_LCA_POS     (0U)
#define SEC_ENG_SE_SHA_0_LCA_LEN     (32U)
#define SEC_ENG_SE_SHA_0_LCA_MSK     (((1U << SEC_ENG_SE_SHA_0_LCA_LEN) - 1) << SEC_ENG_SE_SHA_0_LCA_POS)
#define SEC_ENG_SE_SHA_0_LCA_UMSK    (~(((1U << SEC_ENG_SE_SHA_0_LCA_LEN) - 1) << SEC_ENG_SE_SHA_0_LCA_POS))

/* 0xFC : se_sha_0_ctrl_prot */
#define SEC_ENG_SE_SHA_0_CTRL_PROT_OFFSET (0xFC)
#define SEC_ENG_SE_SHA_PROT_EN            SEC_ENG_SE_SHA_PROT_EN
#define SEC_ENG_SE_SHA_PROT_EN_POS        (0U)
#define SEC_ENG_SE_SHA_PROT_EN_LEN        (1U)
#define SEC_ENG_SE_SHA_PROT_EN_MSK        (((1U << SEC_ENG_SE_SHA_PROT_EN_LEN) - 1) << SEC_ENG_SE_SHA_PROT_EN_POS)
#define SEC_ENG_SE_SHA_PROT_EN_UMSK       (~(((1U << SEC_ENG_SE_SHA_PROT_EN_LEN) - 1) << SEC_ENG_SE_SHA_PROT_EN_POS))
#define SEC_ENG_SE_SHA_ID0_EN             SEC_ENG_SE_SHA_ID0_EN
#define SEC_ENG_SE_SHA_ID0_EN_POS         (1U)
#define SEC_ENG_SE_SHA_ID0_EN_LEN         (1U)
#define SEC_ENG_SE_SHA_ID0_EN_MSK         (((1U << SEC_ENG_SE_SHA_ID0_EN_LEN) - 1) << SEC_ENG_SE_SHA_ID0_EN_POS)
#define SEC_ENG_SE_SHA_ID0_EN_UMSK        (~(((1U << SEC_ENG_SE_SHA_ID0_EN_LEN) - 1) << SEC_ENG_SE_SHA_ID0_EN_POS))
#define SEC_ENG_SE_SHA_ID1_EN             SEC_ENG_SE_SHA_ID1_EN
#define SEC_ENG_SE_SHA_ID1_EN_POS         (2U)
#define SEC_ENG_SE_SHA_ID1_EN_LEN         (1U)
#define SEC_ENG_SE_SHA_ID1_EN_MSK         (((1U << SEC_ENG_SE_SHA_ID1_EN_LEN) - 1) << SEC_ENG_SE_SHA_ID1_EN_POS)
#define SEC_ENG_SE_SHA_ID1_EN_UMSK        (~(((1U << SEC_ENG_SE_SHA_ID1_EN_LEN) - 1) << SEC_ENG_SE_SHA_ID1_EN_POS))

/* 0x100 : se_aes_0_ctrl */
#define SEC_ENG_SE_AES_0_CTRL_OFFSET      (0x100)
#define SEC_ENG_SE_AES_0_BUSY             SEC_ENG_SE_AES_0_BUSY
#define SEC_ENG_SE_AES_0_BUSY_POS         (0U)
#define SEC_ENG_SE_AES_0_BUSY_LEN         (1U)
#define SEC_ENG_SE_AES_0_BUSY_MSK         (((1U << SEC_ENG_SE_AES_0_BUSY_LEN) - 1) << SEC_ENG_SE_AES_0_BUSY_POS)
#define SEC_ENG_SE_AES_0_BUSY_UMSK        (~(((1U << SEC_ENG_SE_AES_0_BUSY_LEN) - 1) << SEC_ENG_SE_AES_0_BUSY_POS))
#define SEC_ENG_SE_AES_0_TRIG_1T          SEC_ENG_SE_AES_0_TRIG_1T
#define SEC_ENG_SE_AES_0_TRIG_1T_POS      (1U)
#define SEC_ENG_SE_AES_0_TRIG_1T_LEN      (1U)
#define SEC_ENG_SE_AES_0_TRIG_1T_MSK      (((1U << SEC_ENG_SE_AES_0_TRIG_1T_LEN) - 1) << SEC_ENG_SE_AES_0_TRIG_1T_POS)
#define SEC_ENG_SE_AES_0_TRIG_1T_UMSK     (~(((1U << SEC_ENG_SE_AES_0_TRIG_1T_LEN) - 1) << SEC_ENG_SE_AES_0_TRIG_1T_POS))
#define SEC_ENG_SE_AES_0_EN               SEC_ENG_SE_AES_0_EN
#define SEC_ENG_SE_AES_0_EN_POS           (2U)
#define SEC_ENG_SE_AES_0_EN_LEN           (1U)
#define SEC_ENG_SE_AES_0_EN_MSK           (((1U << SEC_ENG_SE_AES_0_EN_LEN) - 1) << SEC_ENG_SE_AES_0_EN_POS)
#define SEC_ENG_SE_AES_0_EN_UMSK          (~(((1U << SEC_ENG_SE_AES_0_EN_LEN) - 1) << SEC_ENG_SE_AES_0_EN_POS))
#define SEC_ENG_SE_AES_0_MODE             SEC_ENG_SE_AES_0_MODE
#define SEC_ENG_SE_AES_0_MODE_POS         (3U)
#define SEC_ENG_SE_AES_0_MODE_LEN         (2U)
#define SEC_ENG_SE_AES_0_MODE_MSK         (((1U << SEC_ENG_SE_AES_0_MODE_LEN) - 1) << SEC_ENG_SE_AES_0_MODE_POS)
#define SEC_ENG_SE_AES_0_MODE_UMSK        (~(((1U << SEC_ENG_SE_AES_0_MODE_LEN) - 1) << SEC_ENG_SE_AES_0_MODE_POS))
#define SEC_ENG_SE_AES_0_DEC_EN           SEC_ENG_SE_AES_0_DEC_EN
#define SEC_ENG_SE_AES_0_DEC_EN_POS       (5U)
#define SEC_ENG_SE_AES_0_DEC_EN_LEN       (1U)
#define SEC_ENG_SE_AES_0_DEC_EN_MSK       (((1U << SEC_ENG_SE_AES_0_DEC_EN_LEN) - 1) << SEC_ENG_SE_AES_0_DEC_EN_POS)
#define SEC_ENG_SE_AES_0_DEC_EN_UMSK      (~(((1U << SEC_ENG_SE_AES_0_DEC_EN_LEN) - 1) << SEC_ENG_SE_AES_0_DEC_EN_POS))
#define SEC_ENG_SE_AES_0_DEC_KEY_SEL      SEC_ENG_SE_AES_0_DEC_KEY_SEL
#define SEC_ENG_SE_AES_0_DEC_KEY_SEL_POS  (6U)
#define SEC_ENG_SE_AES_0_DEC_KEY_SEL_LEN  (1U)
#define SEC_ENG_SE_AES_0_DEC_KEY_SEL_MSK  (((1U << SEC_ENG_SE_AES_0_DEC_KEY_SEL_LEN) - 1) << SEC_ENG_SE_AES_0_DEC_KEY_SEL_POS)
#define SEC_ENG_SE_AES_0_DEC_KEY_SEL_UMSK (~(((1U << SEC_ENG_SE_AES_0_DEC_KEY_SEL_LEN) - 1) << SEC_ENG_SE_AES_0_DEC_KEY_SEL_POS))
#define SEC_ENG_SE_AES_0_HW_KEY_EN        SEC_ENG_SE_AES_0_HW_KEY_EN
#define SEC_ENG_SE_AES_0_HW_KEY_EN_POS    (7U)
#define SEC_ENG_SE_AES_0_HW_KEY_EN_LEN    (1U)
#define SEC_ENG_SE_AES_0_HW_KEY_EN_MSK    (((1U << SEC_ENG_SE_AES_0_HW_KEY_EN_LEN) - 1) << SEC_ENG_SE_AES_0_HW_KEY_EN_POS)
#define SEC_ENG_SE_AES_0_HW_KEY_EN_UMSK   (~(((1U << SEC_ENG_SE_AES_0_HW_KEY_EN_LEN) - 1) << SEC_ENG_SE_AES_0_HW_KEY_EN_POS))
#define SEC_ENG_SE_AES_0_INT              SEC_ENG_SE_AES_0_INT
#define SEC_ENG_SE_AES_0_INT_POS          (8U)
#define SEC_ENG_SE_AES_0_INT_LEN          (1U)
#define SEC_ENG_SE_AES_0_INT_MSK          (((1U << SEC_ENG_SE_AES_0_INT_LEN) - 1) << SEC_ENG_SE_AES_0_INT_POS)
#define SEC_ENG_SE_AES_0_INT_UMSK         (~(((1U << SEC_ENG_SE_AES_0_INT_LEN) - 1) << SEC_ENG_SE_AES_0_INT_POS))
#define SEC_ENG_SE_AES_0_INT_CLR_1T       SEC_ENG_SE_AES_0_INT_CLR_1T
#define SEC_ENG_SE_AES_0_INT_CLR_1T_POS   (9U)
#define SEC_ENG_SE_AES_0_INT_CLR_1T_LEN   (1U)
#define SEC_ENG_SE_AES_0_INT_CLR_1T_MSK   (((1U << SEC_ENG_SE_AES_0_INT_CLR_1T_LEN) - 1) << SEC_ENG_SE_AES_0_INT_CLR_1T_POS)
#define SEC_ENG_SE_AES_0_INT_CLR_1T_UMSK  (~(((1U << SEC_ENG_SE_AES_0_INT_CLR_1T_LEN) - 1) << SEC_ENG_SE_AES_0_INT_CLR_1T_POS))
#define SEC_ENG_SE_AES_0_INT_SET_1T       SEC_ENG_SE_AES_0_INT_SET_1T
#define SEC_ENG_SE_AES_0_INT_SET_1T_POS   (10U)
#define SEC_ENG_SE_AES_0_INT_SET_1T_LEN   (1U)
#define SEC_ENG_SE_AES_0_INT_SET_1T_MSK   (((1U << SEC_ENG_SE_AES_0_INT_SET_1T_LEN) - 1) << SEC_ENG_SE_AES_0_INT_SET_1T_POS)
#define SEC_ENG_SE_AES_0_INT_SET_1T_UMSK  (~(((1U << SEC_ENG_SE_AES_0_INT_SET_1T_LEN) - 1) << SEC_ENG_SE_AES_0_INT_SET_1T_POS))
#define SEC_ENG_SE_AES_0_INT_MASK         SEC_ENG_SE_AES_0_INT_MASK
#define SEC_ENG_SE_AES_0_INT_MASK_POS     (11U)
#define SEC_ENG_SE_AES_0_INT_MASK_LEN     (1U)
#define SEC_ENG_SE_AES_0_INT_MASK_MSK     (((1U << SEC_ENG_SE_AES_0_INT_MASK_LEN) - 1) << SEC_ENG_SE_AES_0_INT_MASK_POS)
#define SEC_ENG_SE_AES_0_INT_MASK_UMSK    (~(((1U << SEC_ENG_SE_AES_0_INT_MASK_LEN) - 1) << SEC_ENG_SE_AES_0_INT_MASK_POS))
#define SEC_ENG_SE_AES_0_BLOCK_MODE       SEC_ENG_SE_AES_0_BLOCK_MODE
#define SEC_ENG_SE_AES_0_BLOCK_MODE_POS   (12U)
#define SEC_ENG_SE_AES_0_BLOCK_MODE_LEN   (2U)
#define SEC_ENG_SE_AES_0_BLOCK_MODE_MSK   (((1U << SEC_ENG_SE_AES_0_BLOCK_MODE_LEN) - 1) << SEC_ENG_SE_AES_0_BLOCK_MODE_POS)
#define SEC_ENG_SE_AES_0_BLOCK_MODE_UMSK  (~(((1U << SEC_ENG_SE_AES_0_BLOCK_MODE_LEN) - 1) << SEC_ENG_SE_AES_0_BLOCK_MODE_POS))
#define SEC_ENG_SE_AES_0_IV_SEL           SEC_ENG_SE_AES_0_IV_SEL
#define SEC_ENG_SE_AES_0_IV_SEL_POS       (14U)
#define SEC_ENG_SE_AES_0_IV_SEL_LEN       (1U)
#define SEC_ENG_SE_AES_0_IV_SEL_MSK       (((1U << SEC_ENG_SE_AES_0_IV_SEL_LEN) - 1) << SEC_ENG_SE_AES_0_IV_SEL_POS)
#define SEC_ENG_SE_AES_0_IV_SEL_UMSK      (~(((1U << SEC_ENG_SE_AES_0_IV_SEL_LEN) - 1) << SEC_ENG_SE_AES_0_IV_SEL_POS))
#define SEC_ENG_SE_AES_0_LINK_MODE        SEC_ENG_SE_AES_0_LINK_MODE
#define SEC_ENG_SE_AES_0_LINK_MODE_POS    (15U)
#define SEC_ENG_SE_AES_0_LINK_MODE_LEN    (1U)
#define SEC_ENG_SE_AES_0_LINK_MODE_MSK    (((1U << SEC_ENG_SE_AES_0_LINK_MODE_LEN) - 1) << SEC_ENG_SE_AES_0_LINK_MODE_POS)
#define SEC_ENG_SE_AES_0_LINK_MODE_UMSK   (~(((1U << SEC_ENG_SE_AES_0_LINK_MODE_LEN) - 1) << SEC_ENG_SE_AES_0_LINK_MODE_POS))
#define SEC_ENG_SE_AES_0_MSG_LEN          SEC_ENG_SE_AES_0_MSG_LEN
#define SEC_ENG_SE_AES_0_MSG_LEN_POS      (16U)
#define SEC_ENG_SE_AES_0_MSG_LEN_LEN      (16U)
#define SEC_ENG_SE_AES_0_MSG_LEN_MSK      (((1U << SEC_ENG_SE_AES_0_MSG_LEN_LEN) - 1) << SEC_ENG_SE_AES_0_MSG_LEN_POS)
#define SEC_ENG_SE_AES_0_MSG_LEN_UMSK     (~(((1U << SEC_ENG_SE_AES_0_MSG_LEN_LEN) - 1) << SEC_ENG_SE_AES_0_MSG_LEN_POS))

/* 0x104 : se_aes_0_msa */
#define SEC_ENG_SE_AES_0_MSA_OFFSET (0x104)
#define SEC_ENG_SE_AES_0_MSA        SEC_ENG_SE_AES_0_MSA
#define SEC_ENG_SE_AES_0_MSA_POS    (0U)
#define SEC_ENG_SE_AES_0_MSA_LEN    (32U)
#define SEC_ENG_SE_AES_0_MSA_MSK    (((1U << SEC_ENG_SE_AES_0_MSA_LEN) - 1) << SEC_ENG_SE_AES_0_MSA_POS)
#define SEC_ENG_SE_AES_0_MSA_UMSK   (~(((1U << SEC_ENG_SE_AES_0_MSA_LEN) - 1) << SEC_ENG_SE_AES_0_MSA_POS))

/* 0x108 : se_aes_0_mda */
#define SEC_ENG_SE_AES_0_MDA_OFFSET (0x108)
#define SEC_ENG_SE_AES_0_MDA        SEC_ENG_SE_AES_0_MDA
#define SEC_ENG_SE_AES_0_MDA_POS    (0U)
#define SEC_ENG_SE_AES_0_MDA_LEN    (32U)
#define SEC_ENG_SE_AES_0_MDA_MSK    (((1U << SEC_ENG_SE_AES_0_MDA_LEN) - 1) << SEC_ENG_SE_AES_0_MDA_POS)
#define SEC_ENG_SE_AES_0_MDA_UMSK   (~(((1U << SEC_ENG_SE_AES_0_MDA_LEN) - 1) << SEC_ENG_SE_AES_0_MDA_POS))

/* 0x10C : se_aes_0_status */
#define SEC_ENG_SE_AES_0_STATUS_OFFSET (0x10C)
#define SEC_ENG_SE_AES_0_STATUS        SEC_ENG_SE_AES_0_STATUS
#define SEC_ENG_SE_AES_0_STATUS_POS    (0U)
#define SEC_ENG_SE_AES_0_STATUS_LEN    (32U)
#define SEC_ENG_SE_AES_0_STATUS_MSK    (((1U << SEC_ENG_SE_AES_0_STATUS_LEN) - 1) << SEC_ENG_SE_AES_0_STATUS_POS)
#define SEC_ENG_SE_AES_0_STATUS_UMSK   (~(((1U << SEC_ENG_SE_AES_0_STATUS_LEN) - 1) << SEC_ENG_SE_AES_0_STATUS_POS))

/* 0x110 : se_aes_0_iv_0 */
#define SEC_ENG_SE_AES_0_IV_0_OFFSET (0x110)
#define SEC_ENG_SE_AES_0_IV_0        SEC_ENG_SE_AES_0_IV_0
#define SEC_ENG_SE_AES_0_IV_0_POS    (0U)
#define SEC_ENG_SE_AES_0_IV_0_LEN    (32U)
#define SEC_ENG_SE_AES_0_IV_0_MSK    (((1U << SEC_ENG_SE_AES_0_IV_0_LEN) - 1) << SEC_ENG_SE_AES_0_IV_0_POS)
#define SEC_ENG_SE_AES_0_IV_0_UMSK   (~(((1U << SEC_ENG_SE_AES_0_IV_0_LEN) - 1) << SEC_ENG_SE_AES_0_IV_0_POS))

/* 0x114 : se_aes_0_iv_1 */
#define SEC_ENG_SE_AES_0_IV_1_OFFSET (0x114)
#define SEC_ENG_SE_AES_0_IV_1        SEC_ENG_SE_AES_0_IV_1
#define SEC_ENG_SE_AES_0_IV_1_POS    (0U)
#define SEC_ENG_SE_AES_0_IV_1_LEN    (32U)
#define SEC_ENG_SE_AES_0_IV_1_MSK    (((1U << SEC_ENG_SE_AES_0_IV_1_LEN) - 1) << SEC_ENG_SE_AES_0_IV_1_POS)
#define SEC_ENG_SE_AES_0_IV_1_UMSK   (~(((1U << SEC_ENG_SE_AES_0_IV_1_LEN) - 1) << SEC_ENG_SE_AES_0_IV_1_POS))

/* 0x118 : se_aes_0_iv_2 */
#define SEC_ENG_SE_AES_0_IV_2_OFFSET (0x118)
#define SEC_ENG_SE_AES_0_IV_2        SEC_ENG_SE_AES_0_IV_2
#define SEC_ENG_SE_AES_0_IV_2_POS    (0U)
#define SEC_ENG_SE_AES_0_IV_2_LEN    (32U)
#define SEC_ENG_SE_AES_0_IV_2_MSK    (((1U << SEC_ENG_SE_AES_0_IV_2_LEN) - 1) << SEC_ENG_SE_AES_0_IV_2_POS)
#define SEC_ENG_SE_AES_0_IV_2_UMSK   (~(((1U << SEC_ENG_SE_AES_0_IV_2_LEN) - 1) << SEC_ENG_SE_AES_0_IV_2_POS))

/* 0x11C : se_aes_0_iv_3 */
#define SEC_ENG_SE_AES_0_IV_3_OFFSET (0x11C)
#define SEC_ENG_SE_AES_0_IV_3        SEC_ENG_SE_AES_0_IV_3
#define SEC_ENG_SE_AES_0_IV_3_POS    (0U)
#define SEC_ENG_SE_AES_0_IV_3_LEN    (32U)
#define SEC_ENG_SE_AES_0_IV_3_MSK    (((1U << SEC_ENG_SE_AES_0_IV_3_LEN) - 1) << SEC_ENG_SE_AES_0_IV_3_POS)
#define SEC_ENG_SE_AES_0_IV_3_UMSK   (~(((1U << SEC_ENG_SE_AES_0_IV_3_LEN) - 1) << SEC_ENG_SE_AES_0_IV_3_POS))

/* 0x120 : se_aes_0_key_0 */
#define SEC_ENG_SE_AES_0_KEY_0_OFFSET (0x120)
#define SEC_ENG_SE_AES_0_KEY_0        SEC_ENG_SE_AES_0_KEY_0
#define SEC_ENG_SE_AES_0_KEY_0_POS    (0U)
#define SEC_ENG_SE_AES_0_KEY_0_LEN    (32U)
#define SEC_ENG_SE_AES_0_KEY_0_MSK    (((1U << SEC_ENG_SE_AES_0_KEY_0_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_0_POS)
#define SEC_ENG_SE_AES_0_KEY_0_UMSK   (~(((1U << SEC_ENG_SE_AES_0_KEY_0_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_0_POS))

/* 0x124 : se_aes_0_key_1 */
#define SEC_ENG_SE_AES_0_KEY_1_OFFSET (0x124)
#define SEC_ENG_SE_AES_0_KEY_1        SEC_ENG_SE_AES_0_KEY_1
#define SEC_ENG_SE_AES_0_KEY_1_POS    (0U)
#define SEC_ENG_SE_AES_0_KEY_1_LEN    (32U)
#define SEC_ENG_SE_AES_0_KEY_1_MSK    (((1U << SEC_ENG_SE_AES_0_KEY_1_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_1_POS)
#define SEC_ENG_SE_AES_0_KEY_1_UMSK   (~(((1U << SEC_ENG_SE_AES_0_KEY_1_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_1_POS))

/* 0x128 : se_aes_0_key_2 */
#define SEC_ENG_SE_AES_0_KEY_2_OFFSET (0x128)
#define SEC_ENG_SE_AES_0_KEY_2        SEC_ENG_SE_AES_0_KEY_2
#define SEC_ENG_SE_AES_0_KEY_2_POS    (0U)
#define SEC_ENG_SE_AES_0_KEY_2_LEN    (32U)
#define SEC_ENG_SE_AES_0_KEY_2_MSK    (((1U << SEC_ENG_SE_AES_0_KEY_2_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_2_POS)
#define SEC_ENG_SE_AES_0_KEY_2_UMSK   (~(((1U << SEC_ENG_SE_AES_0_KEY_2_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_2_POS))

/* 0x12C : se_aes_0_key_3 */
#define SEC_ENG_SE_AES_0_KEY_3_OFFSET (0x12C)
#define SEC_ENG_SE_AES_0_KEY_3        SEC_ENG_SE_AES_0_KEY_3
#define SEC_ENG_SE_AES_0_KEY_3_POS    (0U)
#define SEC_ENG_SE_AES_0_KEY_3_LEN    (32U)
#define SEC_ENG_SE_AES_0_KEY_3_MSK    (((1U << SEC_ENG_SE_AES_0_KEY_3_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_3_POS)
#define SEC_ENG_SE_AES_0_KEY_3_UMSK   (~(((1U << SEC_ENG_SE_AES_0_KEY_3_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_3_POS))

/* 0x130 : se_aes_0_key_4 */
#define SEC_ENG_SE_AES_0_KEY_4_OFFSET (0x130)
#define SEC_ENG_SE_AES_0_KEY_4        SEC_ENG_SE_AES_0_KEY_4
#define SEC_ENG_SE_AES_0_KEY_4_POS    (0U)
#define SEC_ENG_SE_AES_0_KEY_4_LEN    (32U)
#define SEC_ENG_SE_AES_0_KEY_4_MSK    (((1U << SEC_ENG_SE_AES_0_KEY_4_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_4_POS)
#define SEC_ENG_SE_AES_0_KEY_4_UMSK   (~(((1U << SEC_ENG_SE_AES_0_KEY_4_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_4_POS))

/* 0x134 : se_aes_0_key_5 */
#define SEC_ENG_SE_AES_0_KEY_5_OFFSET (0x134)
#define SEC_ENG_SE_AES_0_KEY_5        SEC_ENG_SE_AES_0_KEY_5
#define SEC_ENG_SE_AES_0_KEY_5_POS    (0U)
#define SEC_ENG_SE_AES_0_KEY_5_LEN    (32U)
#define SEC_ENG_SE_AES_0_KEY_5_MSK    (((1U << SEC_ENG_SE_AES_0_KEY_5_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_5_POS)
#define SEC_ENG_SE_AES_0_KEY_5_UMSK   (~(((1U << SEC_ENG_SE_AES_0_KEY_5_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_5_POS))

/* 0x138 : se_aes_0_key_6 */
#define SEC_ENG_SE_AES_0_KEY_6_OFFSET (0x138)
#define SEC_ENG_SE_AES_0_KEY_6        SEC_ENG_SE_AES_0_KEY_6
#define SEC_ENG_SE_AES_0_KEY_6_POS    (0U)
#define SEC_ENG_SE_AES_0_KEY_6_LEN    (32U)
#define SEC_ENG_SE_AES_0_KEY_6_MSK    (((1U << SEC_ENG_SE_AES_0_KEY_6_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_6_POS)
#define SEC_ENG_SE_AES_0_KEY_6_UMSK   (~(((1U << SEC_ENG_SE_AES_0_KEY_6_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_6_POS))

/* 0x13C : se_aes_0_key_7 */
#define SEC_ENG_SE_AES_0_KEY_7_OFFSET (0x13C)
#define SEC_ENG_SE_AES_0_KEY_7        SEC_ENG_SE_AES_0_KEY_7
#define SEC_ENG_SE_AES_0_KEY_7_POS    (0U)
#define SEC_ENG_SE_AES_0_KEY_7_LEN    (32U)
#define SEC_ENG_SE_AES_0_KEY_7_MSK    (((1U << SEC_ENG_SE_AES_0_KEY_7_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_7_POS)
#define SEC_ENG_SE_AES_0_KEY_7_UMSK   (~(((1U << SEC_ENG_SE_AES_0_KEY_7_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_7_POS))

/* 0x140 : se_aes_0_key_sel_0 */
#define SEC_ENG_SE_AES_0_KEY_SEL_0_OFFSET (0x140)
#define SEC_ENG_SE_AES_0_KEY_SEL_0        SEC_ENG_SE_AES_0_KEY_SEL_0
#define SEC_ENG_SE_AES_0_KEY_SEL_0_POS    (0U)
#define SEC_ENG_SE_AES_0_KEY_SEL_0_LEN    (2U)
#define SEC_ENG_SE_AES_0_KEY_SEL_0_MSK    (((1U << SEC_ENG_SE_AES_0_KEY_SEL_0_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_SEL_0_POS)
#define SEC_ENG_SE_AES_0_KEY_SEL_0_UMSK   (~(((1U << SEC_ENG_SE_AES_0_KEY_SEL_0_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_SEL_0_POS))

/* 0x144 : se_aes_0_key_sel_1 */
#define SEC_ENG_SE_AES_0_KEY_SEL_1_OFFSET (0x144)
#define SEC_ENG_SE_AES_0_KEY_SEL_1        SEC_ENG_SE_AES_0_KEY_SEL_1
#define SEC_ENG_SE_AES_0_KEY_SEL_1_POS    (0U)
#define SEC_ENG_SE_AES_0_KEY_SEL_1_LEN    (2U)
#define SEC_ENG_SE_AES_0_KEY_SEL_1_MSK    (((1U << SEC_ENG_SE_AES_0_KEY_SEL_1_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_SEL_1_POS)
#define SEC_ENG_SE_AES_0_KEY_SEL_1_UMSK   (~(((1U << SEC_ENG_SE_AES_0_KEY_SEL_1_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_SEL_1_POS))

/* 0x148 : se_aes_0_endian */
#define SEC_ENG_SE_AES_0_ENDIAN_OFFSET    (0x148)
#define SEC_ENG_SE_AES_0_DOUT_ENDIAN      SEC_ENG_SE_AES_0_DOUT_ENDIAN
#define SEC_ENG_SE_AES_0_DOUT_ENDIAN_POS  (0U)
#define SEC_ENG_SE_AES_0_DOUT_ENDIAN_LEN  (1U)
#define SEC_ENG_SE_AES_0_DOUT_ENDIAN_MSK  (((1U << SEC_ENG_SE_AES_0_DOUT_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_0_DOUT_ENDIAN_POS)
#define SEC_ENG_SE_AES_0_DOUT_ENDIAN_UMSK (~(((1U << SEC_ENG_SE_AES_0_DOUT_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_0_DOUT_ENDIAN_POS))
#define SEC_ENG_SE_AES_0_DIN_ENDIAN       SEC_ENG_SE_AES_0_DIN_ENDIAN
#define SEC_ENG_SE_AES_0_DIN_ENDIAN_POS   (1U)
#define SEC_ENG_SE_AES_0_DIN_ENDIAN_LEN   (1U)
#define SEC_ENG_SE_AES_0_DIN_ENDIAN_MSK   (((1U << SEC_ENG_SE_AES_0_DIN_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_0_DIN_ENDIAN_POS)
#define SEC_ENG_SE_AES_0_DIN_ENDIAN_UMSK  (~(((1U << SEC_ENG_SE_AES_0_DIN_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_0_DIN_ENDIAN_POS))
#define SEC_ENG_SE_AES_0_KEY_ENDIAN       SEC_ENG_SE_AES_0_KEY_ENDIAN
#define SEC_ENG_SE_AES_0_KEY_ENDIAN_POS   (2U)
#define SEC_ENG_SE_AES_0_KEY_ENDIAN_LEN   (1U)
#define SEC_ENG_SE_AES_0_KEY_ENDIAN_MSK   (((1U << SEC_ENG_SE_AES_0_KEY_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_ENDIAN_POS)
#define SEC_ENG_SE_AES_0_KEY_ENDIAN_UMSK  (~(((1U << SEC_ENG_SE_AES_0_KEY_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_0_KEY_ENDIAN_POS))
#define SEC_ENG_SE_AES_0_IV_ENDIAN        SEC_ENG_SE_AES_0_IV_ENDIAN
#define SEC_ENG_SE_AES_0_IV_ENDIAN_POS    (3U)
#define SEC_ENG_SE_AES_0_IV_ENDIAN_LEN    (1U)
#define SEC_ENG_SE_AES_0_IV_ENDIAN_MSK    (((1U << SEC_ENG_SE_AES_0_IV_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_0_IV_ENDIAN_POS)
#define SEC_ENG_SE_AES_0_IV_ENDIAN_UMSK   (~(((1U << SEC_ENG_SE_AES_0_IV_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_0_IV_ENDIAN_POS))
#define SEC_ENG_SE_AES_0_CTR_LEN          SEC_ENG_SE_AES_0_CTR_LEN
#define SEC_ENG_SE_AES_0_CTR_LEN_POS      (30U)
#define SEC_ENG_SE_AES_0_CTR_LEN_LEN      (2U)
#define SEC_ENG_SE_AES_0_CTR_LEN_MSK      (((1U << SEC_ENG_SE_AES_0_CTR_LEN_LEN) - 1) << SEC_ENG_SE_AES_0_CTR_LEN_POS)
#define SEC_ENG_SE_AES_0_CTR_LEN_UMSK     (~(((1U << SEC_ENG_SE_AES_0_CTR_LEN_LEN) - 1) << SEC_ENG_SE_AES_0_CTR_LEN_POS))

/* 0x14C : se_aes_0_sboot */
#define SEC_ENG_SE_AES_0_SBOOT_OFFSET       (0x14C)
#define SEC_ENG_SE_AES_0_SBOOT_KEY_SEL      SEC_ENG_SE_AES_0_SBOOT_KEY_SEL
#define SEC_ENG_SE_AES_0_SBOOT_KEY_SEL_POS  (0U)
#define SEC_ENG_SE_AES_0_SBOOT_KEY_SEL_LEN  (1U)
#define SEC_ENG_SE_AES_0_SBOOT_KEY_SEL_MSK  (((1U << SEC_ENG_SE_AES_0_SBOOT_KEY_SEL_LEN) - 1) << SEC_ENG_SE_AES_0_SBOOT_KEY_SEL_POS)
#define SEC_ENG_SE_AES_0_SBOOT_KEY_SEL_UMSK (~(((1U << SEC_ENG_SE_AES_0_SBOOT_KEY_SEL_LEN) - 1) << SEC_ENG_SE_AES_0_SBOOT_KEY_SEL_POS))

/* 0x150 : se_aes_0_link */
#define SEC_ENG_SE_AES_0_LINK_OFFSET (0x150)
#define SEC_ENG_SE_AES_0_LCA         SEC_ENG_SE_AES_0_LCA
#define SEC_ENG_SE_AES_0_LCA_POS     (0U)
#define SEC_ENG_SE_AES_0_LCA_LEN     (32U)
#define SEC_ENG_SE_AES_0_LCA_MSK     (((1U << SEC_ENG_SE_AES_0_LCA_LEN) - 1) << SEC_ENG_SE_AES_0_LCA_POS)
#define SEC_ENG_SE_AES_0_LCA_UMSK    (~(((1U << SEC_ENG_SE_AES_0_LCA_LEN) - 1) << SEC_ENG_SE_AES_0_LCA_POS))

/* 0x1FC : se_aes_0_ctrl_prot */
#define SEC_ENG_SE_AES_0_CTRL_PROT_OFFSET (0x1FC)
#define SEC_ENG_SE_AES_PROT_EN            SEC_ENG_SE_AES_PROT_EN
#define SEC_ENG_SE_AES_PROT_EN_POS        (0U)
#define SEC_ENG_SE_AES_PROT_EN_LEN        (1U)
#define SEC_ENG_SE_AES_PROT_EN_MSK        (((1U << SEC_ENG_SE_AES_PROT_EN_LEN) - 1) << SEC_ENG_SE_AES_PROT_EN_POS)
#define SEC_ENG_SE_AES_PROT_EN_UMSK       (~(((1U << SEC_ENG_SE_AES_PROT_EN_LEN) - 1) << SEC_ENG_SE_AES_PROT_EN_POS))
#define SEC_ENG_SE_AES_ID0_EN             SEC_ENG_SE_AES_ID0_EN
#define SEC_ENG_SE_AES_ID0_EN_POS         (1U)
#define SEC_ENG_SE_AES_ID0_EN_LEN         (1U)
#define SEC_ENG_SE_AES_ID0_EN_MSK         (((1U << SEC_ENG_SE_AES_ID0_EN_LEN) - 1) << SEC_ENG_SE_AES_ID0_EN_POS)
#define SEC_ENG_SE_AES_ID0_EN_UMSK        (~(((1U << SEC_ENG_SE_AES_ID0_EN_LEN) - 1) << SEC_ENG_SE_AES_ID0_EN_POS))
#define SEC_ENG_SE_AES_ID1_EN             SEC_ENG_SE_AES_ID1_EN
#define SEC_ENG_SE_AES_ID1_EN_POS         (2U)
#define SEC_ENG_SE_AES_ID1_EN_LEN         (1U)
#define SEC_ENG_SE_AES_ID1_EN_MSK         (((1U << SEC_ENG_SE_AES_ID1_EN_LEN) - 1) << SEC_ENG_SE_AES_ID1_EN_POS)
#define SEC_ENG_SE_AES_ID1_EN_UMSK        (~(((1U << SEC_ENG_SE_AES_ID1_EN_LEN) - 1) << SEC_ENG_SE_AES_ID1_EN_POS))

/* 0x0 : se_aes_ctrl */
#define SEC_ENG_SE_AES_CTRL_OFFSET      (0x0)
#define SEC_ENG_SE_AES_BUSY             SEC_ENG_SE_AES_BUSY
#define SEC_ENG_SE_AES_BUSY_POS         (0U)
#define SEC_ENG_SE_AES_BUSY_LEN         (1U)
#define SEC_ENG_SE_AES_BUSY_MSK         (((1U << SEC_ENG_SE_AES_BUSY_LEN) - 1) << SEC_ENG_SE_AES_BUSY_POS)
#define SEC_ENG_SE_AES_BUSY_UMSK        (~(((1U << SEC_ENG_SE_AES_BUSY_LEN) - 1) << SEC_ENG_SE_AES_BUSY_POS))
#define SEC_ENG_SE_AES_TRIG_1T          SEC_ENG_SE_AES_TRIG_1T
#define SEC_ENG_SE_AES_TRIG_1T_POS      (1U)
#define SEC_ENG_SE_AES_TRIG_1T_LEN      (1U)
#define SEC_ENG_SE_AES_TRIG_1T_MSK      (((1U << SEC_ENG_SE_AES_TRIG_1T_LEN) - 1) << SEC_ENG_SE_AES_TRIG_1T_POS)
#define SEC_ENG_SE_AES_TRIG_1T_UMSK     (~(((1U << SEC_ENG_SE_AES_TRIG_1T_LEN) - 1) << SEC_ENG_SE_AES_TRIG_1T_POS))
#define SEC_ENG_SE_AES_EN               SEC_ENG_SE_AES_EN
#define SEC_ENG_SE_AES_EN_POS           (2U)
#define SEC_ENG_SE_AES_EN_LEN           (1U)
#define SEC_ENG_SE_AES_EN_MSK           (((1U << SEC_ENG_SE_AES_EN_LEN) - 1) << SEC_ENG_SE_AES_EN_POS)
#define SEC_ENG_SE_AES_EN_UMSK          (~(((1U << SEC_ENG_SE_AES_EN_LEN) - 1) << SEC_ENG_SE_AES_EN_POS))
#define SEC_ENG_SE_AES_MODE             SEC_ENG_SE_AES_MODE
#define SEC_ENG_SE_AES_MODE_POS         (3U)
#define SEC_ENG_SE_AES_MODE_LEN         (2U)
#define SEC_ENG_SE_AES_MODE_MSK         (((1U << SEC_ENG_SE_AES_MODE_LEN) - 1) << SEC_ENG_SE_AES_MODE_POS)
#define SEC_ENG_SE_AES_MODE_UMSK        (~(((1U << SEC_ENG_SE_AES_MODE_LEN) - 1) << SEC_ENG_SE_AES_MODE_POS))
#define SEC_ENG_SE_AES_DEC_EN           SEC_ENG_SE_AES_DEC_EN
#define SEC_ENG_SE_AES_DEC_EN_POS       (5U)
#define SEC_ENG_SE_AES_DEC_EN_LEN       (1U)
#define SEC_ENG_SE_AES_DEC_EN_MSK       (((1U << SEC_ENG_SE_AES_DEC_EN_LEN) - 1) << SEC_ENG_SE_AES_DEC_EN_POS)
#define SEC_ENG_SE_AES_DEC_EN_UMSK      (~(((1U << SEC_ENG_SE_AES_DEC_EN_LEN) - 1) << SEC_ENG_SE_AES_DEC_EN_POS))
#define SEC_ENG_SE_AES_DEC_KEY_SEL      SEC_ENG_SE_AES_DEC_KEY_SEL
#define SEC_ENG_SE_AES_DEC_KEY_SEL_POS  (6U)
#define SEC_ENG_SE_AES_DEC_KEY_SEL_LEN  (1U)
#define SEC_ENG_SE_AES_DEC_KEY_SEL_MSK  (((1U << SEC_ENG_SE_AES_DEC_KEY_SEL_LEN) - 1) << SEC_ENG_SE_AES_DEC_KEY_SEL_POS)
#define SEC_ENG_SE_AES_DEC_KEY_SEL_UMSK (~(((1U << SEC_ENG_SE_AES_DEC_KEY_SEL_LEN) - 1) << SEC_ENG_SE_AES_DEC_KEY_SEL_POS))
#define SEC_ENG_SE_AES_HW_KEY_EN        SEC_ENG_SE_AES_HW_KEY_EN
#define SEC_ENG_SE_AES_HW_KEY_EN_POS    (7U)
#define SEC_ENG_SE_AES_HW_KEY_EN_LEN    (1U)
#define SEC_ENG_SE_AES_HW_KEY_EN_MSK    (((1U << SEC_ENG_SE_AES_HW_KEY_EN_LEN) - 1) << SEC_ENG_SE_AES_HW_KEY_EN_POS)
#define SEC_ENG_SE_AES_HW_KEY_EN_UMSK   (~(((1U << SEC_ENG_SE_AES_HW_KEY_EN_LEN) - 1) << SEC_ENG_SE_AES_HW_KEY_EN_POS))
#define SEC_ENG_SE_AES_INT              SEC_ENG_SE_AES_INT
#define SEC_ENG_SE_AES_INT_POS          (8U)
#define SEC_ENG_SE_AES_INT_LEN          (1U)
#define SEC_ENG_SE_AES_INT_MSK          (((1U << SEC_ENG_SE_AES_INT_LEN) - 1) << SEC_ENG_SE_AES_INT_POS)
#define SEC_ENG_SE_AES_INT_UMSK         (~(((1U << SEC_ENG_SE_AES_INT_LEN) - 1) << SEC_ENG_SE_AES_INT_POS))
#define SEC_ENG_SE_AES_INT_CLR_1T       SEC_ENG_SE_AES_INT_CLR_1T
#define SEC_ENG_SE_AES_INT_CLR_1T_POS   (9U)
#define SEC_ENG_SE_AES_INT_CLR_1T_LEN   (1U)
#define SEC_ENG_SE_AES_INT_CLR_1T_MSK   (((1U << SEC_ENG_SE_AES_INT_CLR_1T_LEN) - 1) << SEC_ENG_SE_AES_INT_CLR_1T_POS)
#define SEC_ENG_SE_AES_INT_CLR_1T_UMSK  (~(((1U << SEC_ENG_SE_AES_INT_CLR_1T_LEN) - 1) << SEC_ENG_SE_AES_INT_CLR_1T_POS))
#define SEC_ENG_SE_AES_INT_SET_1T       SEC_ENG_SE_AES_INT_SET_1T
#define SEC_ENG_SE_AES_INT_SET_1T_POS   (10U)
#define SEC_ENG_SE_AES_INT_SET_1T_LEN   (1U)
#define SEC_ENG_SE_AES_INT_SET_1T_MSK   (((1U << SEC_ENG_SE_AES_INT_SET_1T_LEN) - 1) << SEC_ENG_SE_AES_INT_SET_1T_POS)
#define SEC_ENG_SE_AES_INT_SET_1T_UMSK  (~(((1U << SEC_ENG_SE_AES_INT_SET_1T_LEN) - 1) << SEC_ENG_SE_AES_INT_SET_1T_POS))
#define SEC_ENG_SE_AES_INT_MASK         SEC_ENG_SE_AES_INT_MASK
#define SEC_ENG_SE_AES_INT_MASK_POS     (11U)
#define SEC_ENG_SE_AES_INT_MASK_LEN     (1U)
#define SEC_ENG_SE_AES_INT_MASK_MSK     (((1U << SEC_ENG_SE_AES_INT_MASK_LEN) - 1) << SEC_ENG_SE_AES_INT_MASK_POS)
#define SEC_ENG_SE_AES_INT_MASK_UMSK    (~(((1U << SEC_ENG_SE_AES_INT_MASK_LEN) - 1) << SEC_ENG_SE_AES_INT_MASK_POS))
#define SEC_ENG_SE_AES_BLOCK_MODE       SEC_ENG_SE_AES_BLOCK_MODE
#define SEC_ENG_SE_AES_BLOCK_MODE_POS   (12U)
#define SEC_ENG_SE_AES_BLOCK_MODE_LEN   (2U)
#define SEC_ENG_SE_AES_BLOCK_MODE_MSK   (((1U << SEC_ENG_SE_AES_BLOCK_MODE_LEN) - 1) << SEC_ENG_SE_AES_BLOCK_MODE_POS)
#define SEC_ENG_SE_AES_BLOCK_MODE_UMSK  (~(((1U << SEC_ENG_SE_AES_BLOCK_MODE_LEN) - 1) << SEC_ENG_SE_AES_BLOCK_MODE_POS))
#define SEC_ENG_SE_AES_IV_SEL           SEC_ENG_SE_AES_IV_SEL
#define SEC_ENG_SE_AES_IV_SEL_POS       (14U)
#define SEC_ENG_SE_AES_IV_SEL_LEN       (1U)
#define SEC_ENG_SE_AES_IV_SEL_MSK       (((1U << SEC_ENG_SE_AES_IV_SEL_LEN) - 1) << SEC_ENG_SE_AES_IV_SEL_POS)
#define SEC_ENG_SE_AES_IV_SEL_UMSK      (~(((1U << SEC_ENG_SE_AES_IV_SEL_LEN) - 1) << SEC_ENG_SE_AES_IV_SEL_POS))
#define SEC_ENG_SE_AES_LINK_MODE        SEC_ENG_SE_AES_LINK_MODE
#define SEC_ENG_SE_AES_LINK_MODE_POS    (15U)
#define SEC_ENG_SE_AES_LINK_MODE_LEN    (1U)
#define SEC_ENG_SE_AES_LINK_MODE_MSK    (((1U << SEC_ENG_SE_AES_LINK_MODE_LEN) - 1) << SEC_ENG_SE_AES_LINK_MODE_POS)
#define SEC_ENG_SE_AES_LINK_MODE_UMSK   (~(((1U << SEC_ENG_SE_AES_LINK_MODE_LEN) - 1) << SEC_ENG_SE_AES_LINK_MODE_POS))
#define SEC_ENG_SE_AES_MSG_LEN          SEC_ENG_SE_AES_MSG_LEN
#define SEC_ENG_SE_AES_MSG_LEN_POS      (16U)
#define SEC_ENG_SE_AES_MSG_LEN_LEN      (16U)
#define SEC_ENG_SE_AES_MSG_LEN_MSK      (((1U << SEC_ENG_SE_AES_MSG_LEN_LEN) - 1) << SEC_ENG_SE_AES_MSG_LEN_POS)
#define SEC_ENG_SE_AES_MSG_LEN_UMSK     (~(((1U << SEC_ENG_SE_AES_MSG_LEN_LEN) - 1) << SEC_ENG_SE_AES_MSG_LEN_POS))

/* 0x4 : se_aes_msa */
#define SEC_ENG_SE_AES_MSA_OFFSET (0x4)
#define SEC_ENG_SE_AES_MSA        SEC_ENG_SE_AES_MSA
#define SEC_ENG_SE_AES_MSA_POS    (0U)
#define SEC_ENG_SE_AES_MSA_LEN    (32U)
#define SEC_ENG_SE_AES_MSA_MSK    (((1U << SEC_ENG_SE_AES_MSA_LEN) - 1) << SEC_ENG_SE_AES_MSA_POS)
#define SEC_ENG_SE_AES_MSA_UMSK   (~(((1U << SEC_ENG_SE_AES_MSA_LEN) - 1) << SEC_ENG_SE_AES_MSA_POS))

/* 0x8 : se_aes_mda */
#define SEC_ENG_SE_AES_MDA_OFFSET (0x8)
#define SEC_ENG_SE_AES_MDA        SEC_ENG_SE_AES_MDA
#define SEC_ENG_SE_AES_MDA_POS    (0U)
#define SEC_ENG_SE_AES_MDA_LEN    (32U)
#define SEC_ENG_SE_AES_MDA_MSK    (((1U << SEC_ENG_SE_AES_MDA_LEN) - 1) << SEC_ENG_SE_AES_MDA_POS)
#define SEC_ENG_SE_AES_MDA_UMSK   (~(((1U << SEC_ENG_SE_AES_MDA_LEN) - 1) << SEC_ENG_SE_AES_MDA_POS))

/* 0xc : se_aes_status */
#define SEC_ENG_SE_AES_STATUS_OFFSET (0xc)
#define SEC_ENG_SE_AES_STATUS        SEC_ENG_SE_AES_STATUS
#define SEC_ENG_SE_AES_STATUS_POS    (0U)
#define SEC_ENG_SE_AES_STATUS_LEN    (32U)
#define SEC_ENG_SE_AES_STATUS_MSK    (((1U << SEC_ENG_SE_AES_STATUS_LEN) - 1) << SEC_ENG_SE_AES_STATUS_POS)
#define SEC_ENG_SE_AES_STATUS_UMSK   (~(((1U << SEC_ENG_SE_AES_STATUS_LEN) - 1) << SEC_ENG_SE_AES_STATUS_POS))

/* 0x10 : se_aes_iv_0 */
#define SEC_ENG_SE_AES_IV_0_OFFSET (0x10)
#define SEC_ENG_SE_AES_IV_0        SEC_ENG_SE_AES_IV_0
#define SEC_ENG_SE_AES_IV_0_POS    (0U)
#define SEC_ENG_SE_AES_IV_0_LEN    (32U)
#define SEC_ENG_SE_AES_IV_0_MSK    (((1U << SEC_ENG_SE_AES_IV_0_LEN) - 1) << SEC_ENG_SE_AES_IV_0_POS)
#define SEC_ENG_SE_AES_IV_0_UMSK   (~(((1U << SEC_ENG_SE_AES_IV_0_LEN) - 1) << SEC_ENG_SE_AES_IV_0_POS))

/* 0x14 : se_aes_iv_1 */
#define SEC_ENG_SE_AES_IV_1_OFFSET (0x14)
#define SEC_ENG_SE_AES_IV_1        SEC_ENG_SE_AES_IV_1
#define SEC_ENG_SE_AES_IV_1_POS    (0U)
#define SEC_ENG_SE_AES_IV_1_LEN    (32U)
#define SEC_ENG_SE_AES_IV_1_MSK    (((1U << SEC_ENG_SE_AES_IV_1_LEN) - 1) << SEC_ENG_SE_AES_IV_1_POS)
#define SEC_ENG_SE_AES_IV_1_UMSK   (~(((1U << SEC_ENG_SE_AES_IV_1_LEN) - 1) << SEC_ENG_SE_AES_IV_1_POS))

/* 0x18 : se_aes_iv_2 */
#define SEC_ENG_SE_AES_IV_2_OFFSET (0x18)
#define SEC_ENG_SE_AES_IV_2        SEC_ENG_SE_AES_IV_2
#define SEC_ENG_SE_AES_IV_2_POS    (0U)
#define SEC_ENG_SE_AES_IV_2_LEN    (32U)
#define SEC_ENG_SE_AES_IV_2_MSK    (((1U << SEC_ENG_SE_AES_IV_2_LEN) - 1) << SEC_ENG_SE_AES_IV_2_POS)
#define SEC_ENG_SE_AES_IV_2_UMSK   (~(((1U << SEC_ENG_SE_AES_IV_2_LEN) - 1) << SEC_ENG_SE_AES_IV_2_POS))

/* 0x1c : se_aes_iv_3 */
#define SEC_ENG_SE_AES_IV_3_OFFSET (0x1c)
#define SEC_ENG_SE_AES_IV_3        SEC_ENG_SE_AES_IV_3
#define SEC_ENG_SE_AES_IV_3_POS    (0U)
#define SEC_ENG_SE_AES_IV_3_LEN    (32U)
#define SEC_ENG_SE_AES_IV_3_MSK    (((1U << SEC_ENG_SE_AES_IV_3_LEN) - 1) << SEC_ENG_SE_AES_IV_3_POS)
#define SEC_ENG_SE_AES_IV_3_UMSK   (~(((1U << SEC_ENG_SE_AES_IV_3_LEN) - 1) << SEC_ENG_SE_AES_IV_3_POS))

/* 0x20 : se_aes_key_0 */
#define SEC_ENG_SE_AES_KEY_0_OFFSET (0x20)
#define SEC_ENG_SE_AES_KEY_0        SEC_ENG_SE_AES_KEY_0
#define SEC_ENG_SE_AES_KEY_0_POS    (0U)
#define SEC_ENG_SE_AES_KEY_0_LEN    (32U)
#define SEC_ENG_SE_AES_KEY_0_MSK    (((1U << SEC_ENG_SE_AES_KEY_0_LEN) - 1) << SEC_ENG_SE_AES_KEY_0_POS)
#define SEC_ENG_SE_AES_KEY_0_UMSK   (~(((1U << SEC_ENG_SE_AES_KEY_0_LEN) - 1) << SEC_ENG_SE_AES_KEY_0_POS))

/* 0x24 : se_aes_key_1 */
#define SEC_ENG_SE_AES_KEY_1_OFFSET (0x24)
#define SEC_ENG_SE_AES_KEY_1        SEC_ENG_SE_AES_KEY_1
#define SEC_ENG_SE_AES_KEY_1_POS    (0U)
#define SEC_ENG_SE_AES_KEY_1_LEN    (32U)
#define SEC_ENG_SE_AES_KEY_1_MSK    (((1U << SEC_ENG_SE_AES_KEY_1_LEN) - 1) << SEC_ENG_SE_AES_KEY_1_POS)
#define SEC_ENG_SE_AES_KEY_1_UMSK   (~(((1U << SEC_ENG_SE_AES_KEY_1_LEN) - 1) << SEC_ENG_SE_AES_KEY_1_POS))

/* 0x28 : se_aes_key_2 */
#define SEC_ENG_SE_AES_KEY_2_OFFSET (0x28)
#define SEC_ENG_SE_AES_KEY_2        SEC_ENG_SE_AES_KEY_2
#define SEC_ENG_SE_AES_KEY_2_POS    (0U)
#define SEC_ENG_SE_AES_KEY_2_LEN    (32U)
#define SEC_ENG_SE_AES_KEY_2_MSK    (((1U << SEC_ENG_SE_AES_KEY_2_LEN) - 1) << SEC_ENG_SE_AES_KEY_2_POS)
#define SEC_ENG_SE_AES_KEY_2_UMSK   (~(((1U << SEC_ENG_SE_AES_KEY_2_LEN) - 1) << SEC_ENG_SE_AES_KEY_2_POS))

/* 0x2c : se_aes_key_3 */
#define SEC_ENG_SE_AES_KEY_3_OFFSET (0x2c)
#define SEC_ENG_SE_AES_KEY_3        SEC_ENG_SE_AES_KEY_3
#define SEC_ENG_SE_AES_KEY_3_POS    (0U)
#define SEC_ENG_SE_AES_KEY_3_LEN    (32U)
#define SEC_ENG_SE_AES_KEY_3_MSK    (((1U << SEC_ENG_SE_AES_KEY_3_LEN) - 1) << SEC_ENG_SE_AES_KEY_3_POS)
#define SEC_ENG_SE_AES_KEY_3_UMSK   (~(((1U << SEC_ENG_SE_AES_KEY_3_LEN) - 1) << SEC_ENG_SE_AES_KEY_3_POS))

/* 0x30 : se_aes_key_4 */
#define SEC_ENG_SE_AES_KEY_4_OFFSET (0x30)
#define SEC_ENG_SE_AES_KEY_4        SEC_ENG_SE_AES_KEY_4
#define SEC_ENG_SE_AES_KEY_4_POS    (0U)
#define SEC_ENG_SE_AES_KEY_4_LEN    (32U)
#define SEC_ENG_SE_AES_KEY_4_MSK    (((1U << SEC_ENG_SE_AES_KEY_4_LEN) - 1) << SEC_ENG_SE_AES_KEY_4_POS)
#define SEC_ENG_SE_AES_KEY_4_UMSK   (~(((1U << SEC_ENG_SE_AES_KEY_4_LEN) - 1) << SEC_ENG_SE_AES_KEY_4_POS))

/* 0x34 : se_aes_key_5 */
#define SEC_ENG_SE_AES_KEY_5_OFFSET (0x34)
#define SEC_ENG_SE_AES_KEY_5        SEC_ENG_SE_AES_KEY_5
#define SEC_ENG_SE_AES_KEY_5_POS    (0U)
#define SEC_ENG_SE_AES_KEY_5_LEN    (32U)
#define SEC_ENG_SE_AES_KEY_5_MSK    (((1U << SEC_ENG_SE_AES_KEY_5_LEN) - 1) << SEC_ENG_SE_AES_KEY_5_POS)
#define SEC_ENG_SE_AES_KEY_5_UMSK   (~(((1U << SEC_ENG_SE_AES_KEY_5_LEN) - 1) << SEC_ENG_SE_AES_KEY_5_POS))

/* 0x38 : se_aes_key_6 */
#define SEC_ENG_SE_AES_KEY_6_OFFSET (0x38)
#define SEC_ENG_SE_AES_KEY_6        SEC_ENG_SE_AES_KEY_6
#define SEC_ENG_SE_AES_KEY_6_POS    (0U)
#define SEC_ENG_SE_AES_KEY_6_LEN    (32U)
#define SEC_ENG_SE_AES_KEY_6_MSK    (((1U << SEC_ENG_SE_AES_KEY_6_LEN) - 1) << SEC_ENG_SE_AES_KEY_6_POS)
#define SEC_ENG_SE_AES_KEY_6_UMSK   (~(((1U << SEC_ENG_SE_AES_KEY_6_LEN) - 1) << SEC_ENG_SE_AES_KEY_6_POS))

/* 0x3c : se_aes_key_7 */
#define SEC_ENG_SE_AES_KEY_7_OFFSET (0x3c)
#define SEC_ENG_SE_AES_KEY_7        SEC_ENG_SE_AES_KEY_7
#define SEC_ENG_SE_AES_KEY_7_POS    (0U)
#define SEC_ENG_SE_AES_KEY_7_LEN    (32U)
#define SEC_ENG_SE_AES_KEY_7_MSK    (((1U << SEC_ENG_SE_AES_KEY_7_LEN) - 1) << SEC_ENG_SE_AES_KEY_7_POS)
#define SEC_ENG_SE_AES_KEY_7_UMSK   (~(((1U << SEC_ENG_SE_AES_KEY_7_LEN) - 1) << SEC_ENG_SE_AES_KEY_7_POS))

/* 0x40 : se_aes_key_sel_0 */
#define SEC_ENG_SE_AES_KEY_SEL_0_OFFSET (0x40)
#define SEC_ENG_SE_AES_KEY_SEL_0        SEC_ENG_SE_AES_KEY_SEL_0
#define SEC_ENG_SE_AES_KEY_SEL_0_POS    (0U)
#define SEC_ENG_SE_AES_KEY_SEL_0_LEN    (2U)
#define SEC_ENG_SE_AES_KEY_SEL_0_MSK    (((1U << SEC_ENG_SE_AES_KEY_SEL_0_LEN) - 1) << SEC_ENG_SE_AES_KEY_SEL_0_POS)
#define SEC_ENG_SE_AES_KEY_SEL_0_UMSK   (~(((1U << SEC_ENG_SE_AES_KEY_SEL_0_LEN) - 1) << SEC_ENG_SE_AES_KEY_SEL_0_POS))

/* 0x44 : se_aes_key_sel_1 */
#define SEC_ENG_SE_AES_KEY_SEL_1_OFFSET (0x44)
#define SEC_ENG_SE_AES_KEY_SEL_1        SEC_ENG_SE_AES_KEY_SEL_1
#define SEC_ENG_SE_AES_KEY_SEL_1_POS    (0U)
#define SEC_ENG_SE_AES_KEY_SEL_1_LEN    (2U)
#define SEC_ENG_SE_AES_KEY_SEL_1_MSK    (((1U << SEC_ENG_SE_AES_KEY_SEL_1_LEN) - 1) << SEC_ENG_SE_AES_KEY_SEL_1_POS)
#define SEC_ENG_SE_AES_KEY_SEL_1_UMSK   (~(((1U << SEC_ENG_SE_AES_KEY_SEL_1_LEN) - 1) << SEC_ENG_SE_AES_KEY_SEL_1_POS))

/* 0x48 : se_aes_endian */
#define SEC_ENG_SE_AES_ENDIAN_OFFSET    (0x48)
#define SEC_ENG_SE_AES_DOUT_ENDIAN      SEC_ENG_SE_AES_DOUT_ENDIAN
#define SEC_ENG_SE_AES_DOUT_ENDIAN_POS  (0U)
#define SEC_ENG_SE_AES_DOUT_ENDIAN_LEN  (1U)
#define SEC_ENG_SE_AES_DOUT_ENDIAN_MSK  (((1U << SEC_ENG_SE_AES_DOUT_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_DOUT_ENDIAN_POS)
#define SEC_ENG_SE_AES_DOUT_ENDIAN_UMSK (~(((1U << SEC_ENG_SE_AES_DOUT_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_DOUT_ENDIAN_POS))
#define SEC_ENG_SE_AES_DIN_ENDIAN       SEC_ENG_SE_AES_DIN_ENDIAN
#define SEC_ENG_SE_AES_DIN_ENDIAN_POS   (1U)
#define SEC_ENG_SE_AES_DIN_ENDIAN_LEN   (1U)
#define SEC_ENG_SE_AES_DIN_ENDIAN_MSK   (((1U << SEC_ENG_SE_AES_DIN_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_DIN_ENDIAN_POS)
#define SEC_ENG_SE_AES_DIN_ENDIAN_UMSK  (~(((1U << SEC_ENG_SE_AES_DIN_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_DIN_ENDIAN_POS))
#define SEC_ENG_SE_AES_KEY_ENDIAN       SEC_ENG_SE_AES_KEY_ENDIAN
#define SEC_ENG_SE_AES_KEY_ENDIAN_POS   (2U)
#define SEC_ENG_SE_AES_KEY_ENDIAN_LEN   (1U)
#define SEC_ENG_SE_AES_KEY_ENDIAN_MSK   (((1U << SEC_ENG_SE_AES_KEY_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_KEY_ENDIAN_POS)
#define SEC_ENG_SE_AES_KEY_ENDIAN_UMSK  (~(((1U << SEC_ENG_SE_AES_KEY_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_KEY_ENDIAN_POS))
#define SEC_ENG_SE_AES_IV_ENDIAN        SEC_ENG_SE_AES_IV_ENDIAN
#define SEC_ENG_SE_AES_IV_ENDIAN_POS    (3U)
#define SEC_ENG_SE_AES_IV_ENDIAN_LEN    (1U)
#define SEC_ENG_SE_AES_IV_ENDIAN_MSK    (((1U << SEC_ENG_SE_AES_IV_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_IV_ENDIAN_POS)
#define SEC_ENG_SE_AES_IV_ENDIAN_UMSK   (~(((1U << SEC_ENG_SE_AES_IV_ENDIAN_LEN) - 1) << SEC_ENG_SE_AES_IV_ENDIAN_POS))
#define SEC_ENG_SE_AES_CTR_LEN          SEC_ENG_SE_AES_CTR_LEN
#define SEC_ENG_SE_AES_CTR_LEN_POS      (30U)
#define SEC_ENG_SE_AES_CTR_LEN_LEN      (2U)
#define SEC_ENG_SE_AES_CTR_LEN_MSK      (((1U << SEC_ENG_SE_AES_CTR_LEN_LEN) - 1) << SEC_ENG_SE_AES_CTR_LEN_POS)
#define SEC_ENG_SE_AES_CTR_LEN_UMSK     (~(((1U << SEC_ENG_SE_AES_CTR_LEN_LEN) - 1) << SEC_ENG_SE_AES_CTR_LEN_POS))

/* 0x4c : se_aes_sboot */
#define SEC_ENG_SE_AES_SBOOT_OFFSET       (0x4c)
#define SEC_ENG_SE_AES_SBOOT_KEY_SEL      SEC_ENG_SE_AES_SBOOT_KEY_SEL
#define SEC_ENG_SE_AES_SBOOT_KEY_SEL_POS  (0U)
#define SEC_ENG_SE_AES_SBOOT_KEY_SEL_LEN  (1U)
#define SEC_ENG_SE_AES_SBOOT_KEY_SEL_MSK  (((1U << SEC_ENG_SE_AES_SBOOT_KEY_SEL_LEN) - 1) << SEC_ENG_SE_AES_SBOOT_KEY_SEL_POS)
#define SEC_ENG_SE_AES_SBOOT_KEY_SEL_UMSK (~(((1U << SEC_ENG_SE_AES_SBOOT_KEY_SEL_LEN) - 1) << SEC_ENG_SE_AES_SBOOT_KEY_SEL_POS))

/* 0x50 : se_aes_link */
#define SEC_ENG_SE_AES_LINK_OFFSET (0x50)
#define SEC_ENG_SE_AES_LCA         SEC_ENG_SE_AES_LCA
#define SEC_ENG_SE_AES_LCA_POS     (0U)
#define SEC_ENG_SE_AES_LCA_LEN     (32U)
#define SEC_ENG_SE_AES_LCA_MSK     (((1U << SEC_ENG_SE_AES_LCA_LEN) - 1) << SEC_ENG_SE_AES_LCA_POS)
#define SEC_ENG_SE_AES_LCA_UMSK    (~(((1U << SEC_ENG_SE_AES_LCA_LEN) - 1) << SEC_ENG_SE_AES_LCA_POS))

/* 0xfc : se_aes_ctrl_prot */
#define SEC_ENG_SE_AES_CTRL_PROT_OFFSET (0xfc)
#define SEC_ENG_SE_AES_PROT_EN          SEC_ENG_SE_AES_PROT_EN
#define SEC_ENG_SE_AES_PROT_EN_POS      (0U)
#define SEC_ENG_SE_AES_PROT_EN_LEN      (1U)
#define SEC_ENG_SE_AES_PROT_EN_MSK      (((1U << SEC_ENG_SE_AES_PROT_EN_LEN) - 1) << SEC_ENG_SE_AES_PROT_EN_POS)
#define SEC_ENG_SE_AES_PROT_EN_UMSK     (~(((1U << SEC_ENG_SE_AES_PROT_EN_LEN) - 1) << SEC_ENG_SE_AES_PROT_EN_POS))
#define SEC_ENG_SE_AES_ID0_EN           SEC_ENG_SE_AES_ID0_EN
#define SEC_ENG_SE_AES_ID0_EN_POS       (1U)
#define SEC_ENG_SE_AES_ID0_EN_LEN       (1U)
#define SEC_ENG_SE_AES_ID0_EN_MSK       (((1U << SEC_ENG_SE_AES_ID0_EN_LEN) - 1) << SEC_ENG_SE_AES_ID0_EN_POS)
#define SEC_ENG_SE_AES_ID0_EN_UMSK      (~(((1U << SEC_ENG_SE_AES_ID0_EN_LEN) - 1) << SEC_ENG_SE_AES_ID0_EN_POS))
#define SEC_ENG_SE_AES_ID1_EN           SEC_ENG_SE_AES_ID1_EN
#define SEC_ENG_SE_AES_ID1_EN_POS       (2U)
#define SEC_ENG_SE_AES_ID1_EN_LEN       (1U)
#define SEC_ENG_SE_AES_ID1_EN_MSK       (((1U << SEC_ENG_SE_AES_ID1_EN_LEN) - 1) << SEC_ENG_SE_AES_ID1_EN_POS)
#define SEC_ENG_SE_AES_ID1_EN_UMSK      (~(((1U << SEC_ENG_SE_AES_ID1_EN_LEN) - 1) << SEC_ENG_SE_AES_ID1_EN_POS))

inline uint32_t __REV(uint32_t value)
{
    uint32_t res = 0;
    res = (value << 24) | (value >> 24);
    res &= 0xFF0000FF; /* only for sure */
    res |= ((value >> 8) & 0x0000FF00) | ((value << 8) & 0x00FF0000);
    return res;
}

struct __metal_driver_vtable_bl_secure0 {
    const struct metal_secure_vtable secure;
};

struct __metal_driver_bl_secure0;

__METAL_DECLARE_VTABLE(__metal_driver_vtable_bl_secure0)

struct __metal_driver_bl_secure0 {
    const struct metal_secure secure;
};

#endif
